cognitedata/pygen

cognite/pygen/dm_clients/README.md

Fix library name
It seems the library name has changed from cognite-gql-pygen to cognite-pygen.
This PR changes the README  to reflect that.

Fix library reference in doc 

---

.github/workflows/release.yaml

ci: only run unit tests upon release

---

cognite/pygen/_generator.py
docs/CHANGELOG.md

[PYG-59] Default clean in generate notebook

---

tests/test_unit/test_generator/test_generate_api_client.py
tests/test_unit/test_generator/test_generate_core.py
tests/test_unit/test_generator/test_sdk_generator_equipment_unit_sdk.py

[PYG-35] tests: run test in cicd

---

examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api/_core.py
examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api/unit_procedure.py
examples-pydantic-v1/omni_multi_pydantic_v1/_api/_core.py
examples-pydantic-v1/omni_pydantic_v1/_api/_core.py
examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_a.py
examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_b.py
examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_c.py
examples-pydantic-v1/omni_pydantic_v1/_api/dependent_on_non_writable.py
examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api/_core.py
examples-pydantic-v1/windmill_pydantic_v1/_api/_core.py
examples-pydantic-v1/windmill_pydantic_v1/_api/blade.py
examples-pydantic-v1/windmill_pydantic_v1/_api/windmill.py

refator; regen v1 SDSs

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/workflows/build.yml
tests/test_integration/conftest.py

[PYG-144, PYG-139] Setup coverage test

---

tests/test_unit/test_models/test_fields/test_connections.py

[PYG-176] 🤸 Debt standardize connection classes Part 2

---

cognite/pygen/_core/models/data_classes.py
cognite/pygen/_core/templates/typed_classes.py.jinja
cognite/pygen/utils/text.py

[PYG-197] 🖌 Style fixes typed

---

cognite/pygen/_core/models/data_classes.py
cognite/pygen/_core/models/fields/connections.py
cognite/pygen/_core/templates/api_class_node.py.jinja
cognite/pygen/_core/templates/data_class_node.py.jinja
docs/CHANGELOG.md
examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_a.py
examples-pydantic-v1/omni_pydantic_v1/data_classes/_connection_item_e.py
examples-pydantic-v1/windmill_pydantic_v1/_api/windmill.py
examples/omni/_api/connection_item_a.py
examples/omni/data_classes/_connection_item_e.py
examples/windmill/_api/windmill.py
tests/test_unit/test_models/test_fields_connections.py

[PYG-199] 🦔Edge

---

cognite/pygen/_core/models/api_classes.py
cognite/pygen/utils/text.py
docs/CHANGELOG.md
tests/test_unit/test_api/test_generate_sdk.py

[PYG-125] 🐼Fix hyphen and start with digit in Python property names

---

cognite/pygen/_build.py
cognite/pygen/_generator.py
docs/cognite_functions.md
docs/installation.md
mkdocs.yml
tests/test_unit_slow/test_generator/test_build.py

[PYG-19]💡Use with Cognite Functions

---

cognite/pygen/_core/generators.py
cognite/pygen/_core/templates/typed_classes.py.jinja
cognite/pygen/_generator.py

[PYG-224] 🤦Hack for skipping readonly fields in Typed Classes

---

cognite/pygen/_generator.py
cognite/pygen/_warnings.py

[PYG-286] Fix not more warnings on core model.

---

docs/requirements.txt

Can be removed when https://github.com/jupyter/nbconvert/issues/2198 is fixed.

👷Fix docs build, freeze mistune to 3.0.2

---

cognite/pygen/_generator.py

[PYG-348]  🤕 fix: ensure output dir is a path

---

examples/cognite_core/_api_client.py
examples/omni/_api_client.py
examples/omni_multi/_api_client.py
examples/omni_sub/_api_client.py
examples/wind_turbine/_api_client.py
poetry.lock
pyproject.toml
tests/test_integration/test_aggregate.py
tests/test_integration/test_query_execution.py

The bug is actually in the PySDK: https://github.com/cognitedata/cognite-sdk-python/pull/2124. This has been fixed. This PR updates the minimum version of the `cognite-sdk` when using Pygen and includes a test for the use case to ensure we do not get a recursion.

[PYG-350] 😣 Fix aggregate empty filter

---

cognite/pygen/_generator.py

The current code assumes that the views are using `PascalCase` in CDF. The fix looks up what is available in the module and the helper message based on that.
Note that I do not trigger a new release for this one as it is no change in behavior, only a helper text.

[PYG-356] ✍🏼 Typo in helper text

---

cognite/pygen/_core/templates/data_class_edge.py.jinja
tests/test_unit/test_api/test_generate_sdk.py

- Generating an SDK no longer raises a `jinja2.exceptions.UndefinedError` if the data model contains a view that is `used_for=edge/all` and contains a reverse direct relation property.

[PYG-362] 🤔Property edge with reverse direct relation property.

---

cognite/pygen/_build.py
tests/test_unit_slow/test_generator/test_build.py

See changelog
- When calling the `build_wheel` method, the resulting wheel will now have the data model version in the filename.

[PYG-376] 👹 Include version in wheel

---

cognite/pygen/_core/models/data_classes.py
examples/cognite_core/data_classes/_cognite_360_image_annotation.py
examples/cognite_core/data_classes/_cognite_360_image_collection.py
examples/cognite_core/data_classes/_cognite_cad_revision.py
examples/cognite_core/data_classes/_cognite_point_cloud_revision.py
tests/test_unit/test_api/test_generate_sdk.py

**Reviewer** 12 lines code fix, rest is test data.
- When generating an SDK with views that overwrites parent properties, `pygen` now includes the overwritten field in the child classes. For example, if you have a `Batch` view that implements `CogniteActivity` and overwrites the `assets` property to be of value type  `MyAsset`, `pygen` will now retrieve `MyAsset`s instead of `CogniteAsset`.

[PYG-385] 😦 Unexpected retrieve behavior

---

.github/workflows/release.yaml

Bug in ci so repeating last PR changelog and bump  to get it released.
- When generating an SDK with views that overwrites parent properties, `pygen` now includes the overwritten field in the child classes. For example, if you have a `Batch` view that implements `CogniteActivity` and overwrites the `assets` property to be of value type  `MyAsset`, `pygen` will now retrieve `MyAsset`s instead of `CogniteAsset`.

ci: fix twine upload

---

.github/workflows/build.yml
pyproject.toml
uv.lock

See changelog below.
- Sets the lower-bound on `typing-extensions` to `4.14.0`. The motivation for this is that currently installing pygen in a `pyodide` environment causes a `ValueError: Requested 'typing-extensions>=4.14.0', but typing-extensions==4.11.0 is already installed`. By setting lower-bound should force `pyodide` to download the correct version of `typing-extensions`.

Lower-bound on typing-extension

---

.github/CODEOWNERS

Transfer the pygen repo from the `iknow` team to the `partner-enablement` and `atlas-ai` teams.

➡New owner

---

docs/what_is_pygen.md

Fix a couple of grammar mistakes.  Nothing more.

Typo fixes to what_is_pygen

---

cognite/pygen/_core/templates/data_classes_core_base.py.jinja
examples/cognite_core/_api/cognite_360_image_model.py
examples/cognite_core/_api/cognite_cad_model.py
examples/cognite_core/_api/cognite_point_cloud_model.py
examples/cognite_core/data_classes/_cognite_360_image_model.py
examples/cognite_core/data_classes/_cognite_cad_model.py
examples/cognite_core/data_classes/_cognite_point_cloud_model.py
examples/cognite_core/data_classes/_core/base.py
examples/omni/data_classes/_core/base.py
examples/omni_multi/data_classes/_core/base.py
examples/omni_sub/data_classes/_core/base.py
examples/wind_turbine/data_classes/_core/base.py
tests/test_unit/test_resulting_sdk/test_data_class.py

The current as write logic fails to account for TimeSeries/FileMetadata/Sequence references in the view.
- In the generated SDK, the `.as_write(...)` field no longer fails for data classes that uses CDF external reference fields.

[PYG-407] 🐜As write fails for CDF external references.

---

cdf.toml
cdf/modules/models/omni/data_models/omni.datamodel.yaml
cdf/modules/models/omni/data_models/omni/views/ConnectionItemH.view.yaml
examples/cognite_core/_api_client.py
examples/omni/_api/__init__.py
examples/omni/_api/_core.py
examples/omni/_api/connection_item_h.py
examples/omni/_api_client.py
examples/omni/data_classes/__init__.py
examples/omni/data_classes/_connection_item_h.py
examples/omni_multi/_api_client.py
examples/omni_sub/_api_client.py
examples/wind_turbine/_api_client.py
pyproject.toml
tests/data/models/Omni/model.yaml
uv.lock

**Reviewer**: All code inside `examples/` is generated. This PR thus contains 0 lines of Python, only 44 lines of YAML with the new view definition. There is no change to the Pygen package only test data - thus should be zero risk.
**Context**: `Omni` is a data model designed to test `pygen`. It covers all possible value types, connections, as well as different types of uses of implements. 
This PR extends this model with a new view `ConnectionItemH`. This has a direct relations to a parent view. The intention of this is to be able to test that when calling the `.as_write()` method that take a response DTO (data transfer object) and converts it to a request DTO, then if the direct relation is a child view that information should persist. Note this PR is only extending the model, the …

[PYG-412] 🧑‍🔧 Extend omni model

---

cognite/pygen/_query/interface.py

In Atlas, we are facing the following issue: for views which are both nodes and edges, when faced with a prompt like "count the maintenance plans where createdBy is greater than 2024-01-01", we will create a query like 
```
{'operation': 'aggregate',
'dataModelView': {'space': 'gsk_montrose_model',
'externalId': 'GskMontroseModel',
'version': 'v1',
'view': 'GskMaintenancePlan'},
'properties': ['name',
'externalId',
'createdTime',
'lastUpdatedTime',
'space'],
'filter': {'and': [{'range': {'property': ['node', 'createdTime'],
'gte': '2024-01-01T00:00:00'}}]}, 
'aggregate': {"properties": {"count":  "externalId"}}
}
```
which, when executed, will give the error 
```
Error: Unknown property: node.space | code: 400 | X-Request-ID: 66856ee8-2067-9a44-b94a-34b1c2852e8a | cluster: westeurope-1 …
```

feat: add instance_types parameter to QueryExecutor
