cognitedata/pygen

.readthedocs.yaml
=> build: added readthedocs file

.readthedocs.yaml, poetry.lock, pyproject.toml
Requires for readthedocs to build from webhook.
=> Docs as optional dependencies.

cognite/pygen/main.py, poetry.lock
Update pydantic version, as previous had a bug. 
=> build: poetry update

examples/movie_domain/client/_api_client.py
=> fix: movie sdk

examples/usage.ipynb
example notebook edited and fixed some spelling and wording
(no need to trigger semver?)
=> some spell-checking

README.md, docs/index.md
=> docs: GitHub badge

README.md, docs/index.md
=> docs: readmefix

docs/quickstart/cdf_notebook.ipynb, docs/quickstart/project.md, mkdocs.yml
=> Minor docs improvements.

docs/quickstart/cdf_notebook.ipynb
=> docs: updated quickstart guide

docs/CHANGELOG.md, docs/quickstart/cdf_notebook.ipynb
=> docs: Improved 

docs/quickstart/cdf_streamlit.md, mkdocs.yml
=> [PYG-69] docs: Streamlit app

README.md, docs/index.md, docs/quickstart/cdf_streamlit.md, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api_client.py, examples-pydantic-v1/markets_pydantic_v1/client/_api_client.py, examples-pydantic-v1/movie_domain_pydantic_v1/client/_api_client.py, examples/equipment_unit/client/_api_client.py, examples/markets/client/_api_client.py, examples/movie_domain/client/_api_client.py, examples/osdu_wells/client/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/shop/client/_api_client.py, examples/tutorial_apm_simple/client/_api_client.py
=> [PYG-72] Remove disclaimer

cognite/pygen/_core/models/fields.py, cognite/pygen/_generator.py, docs/CHANGELOG.md, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/data_classes/_implementation_1_s_pygen_models.py, examples-pydantic-v1/omni_multi_pydantic_v1/data_classes/_implementation_1_s_pygen_models_other.py, examples-pydantic-v1/omni_multi_pydantic_v1/data_classes/_implementation_1_v_2.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_implementation_1.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_primitive_required.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_primitive_with_defaults.py, examples/omni/data_classes/_implementation_1.py, examples/omni/data_classes/_primitive_required.py, examples/omni/data_classes/_primitive_with_defaults.py, examples/omni_multi/_api_client.py, examples/omni_multi/data_classes/_implementation_1_s_pygen_models.py, examples/omni_multi/data_classes/_implementation_1_s_pygen_models_other.py, examples/omni_multi/data_classes/_implementation_1_v_2.py
=> [PYG-79] Required read fields

cognite/pygen/_generator.py
=> [PYG-8] Option for returning SDK files

README.md, docs/index.md
=> docs: update beta notice

cognite/pygen/_core/templates/api_class_node.py.jinja, cognite/pygen/_core/templates/api_core.py.jinja, docs/CHANGELOG.md, examples/equipment_unit/client/_api/_core.py, examples/equipment_unit/client/_api/unit_procedure.py, examples/omni/_api/_core.py, examples/omni/_api/connection_item_a.py, examples/omni/_api/connection_item_b.py, examples/omni/_api/connection_item_c.py, examples/omni/_api/dependent_on_non_writable.py, examples/omni_multi/_api/_core.py, examples/scenario_instance/client/_api/_core.py, examples/windmill/_api/_core.py, examples/windmill/_api/blade.py, examples/windmill/_api/windmill.py, tests/test_integration/test_upsert.py
=> [PYG-79] The 'edge' case.

cognite/pygen/_core/templates/api_core.py.jinja, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api/_core.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_pydantic_v1/_api/_core.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api/_core.py, examples-pydantic-v1/windmill_pydantic_v1/_api/_core.py, examples/equipment_unit/client/_api/_core.py, examples/omni/_api/_core.py, examples/omni_multi/_api/_core.py, examples/scenario_instance/client/_api/_core.py, examples/windmill/_api/_core.py, tests/test_integration/test_query.py
=> [PYG-114] Fix query direct

.github/workflows/build.yml, cognite/pygen/utils/mock_generator.py, docs/CHANGELOG.md, examples/omni/data_classes/_core.py
=> [PYG-127, PYG-128] Bughunting

cognite/pygen/_core/templates/_api_client_multi_model.py.jinja, cognite/pygen/_core/templates/_api_client_single_model.py.jinja, cognite/pygen/_core/templates/data_classes_core.py.jinja, cognite/pygen/_generator.py, docs/CHANGELOG.md, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api_client.py, examples-pydantic-v1/equipment_unit_pydantic_v1/client/data_classes/_core.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/data_classes/_core.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_core.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/data_classes/_core.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/data_classes/_core.py, examples/equipment_unit/client/_api_client.py, examples/equipment_unit/client/data_classes/_core.py, examples/omni/_api_client.py, examples/omni/data_classes/_core.py, examples/omni_multi/_api_client.py, examples/omni_multi/data_classes/_core.py, examples/scenario_instance/client/_api_client.py, examples/scenario_instance/client/data_classes/_core.py, examples/windmill/_api_client.py, examples/windmill/data_classes/_core.py, tests/test_integration/test_upsert.py
=> [PYG-130, PYG-124] Maximum Recursion Depth

cognite/pygen/_core/generators.py, cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/templates/data_class_edge.py.jinja, cognite/pygen/_core/templates/data_class_node.py.jinja
=> [PYG-129] Model prefix

cognite/pygen/utils/mock_generator.py, docs/usage/creating_deleting.ipynb, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/client/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, mkdocs.yml, poetry.lock
=> [PYG-134] Doc Upsert

cognite/pygen/_core/templates/api_class_query.py.jinja, cognite/pygen/_core/templates/api_core.py.jinja, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api/_core.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_a_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_d_query.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api/_core.py, examples-pydantic-v1/windmill_pydantic_v1/_api/_core.py, examples-pydantic-v1/windmill_pydantic_v1/_api/nacelle_query.py, examples-pydantic-v1/windmill_pydantic_v1/_api/windmill_query.py, examples/equipment_unit/client/_api/_core.py, examples/omni/_api/_core.py, examples/omni/_api/connection_item_a_query.py, examples/omni/_api/connection_item_d_query.py, examples/omni_multi/_api/_core.py, examples/scenario_instance/client/_api/_core.py, examples/windmill/_api/_core.py, examples/windmill/_api/nacelle_query.py, examples/windmill/_api/windmill_query.py, tests/test_integration/test_query.py
=> [PYG-138] Respect query limit with direct relations.

cognite/pygen/_core/models/api_casses.py, cognite/pygen/_core/templates/api_class_query.py.jinja, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_b_query.py, examples/omni/_api/connection_item_b_query.py
=> Fix warning self referential views.

cognite/pygen/_core/generators.py, cognite/pygen/_core/models/api_casses.py, cognite/pygen/_core/models/filter_method.py, cognite/pygen/_core/templates/api_class_query.py.jinja, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api/unit_procedure_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_a_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_b_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_c_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_d_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_e_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/dependent_on_non_writable_query.py, examples-pydantic-v1/windmill_pydantic_v1/_api/blade_query.py, examples-pydantic-v1/windmill_pydantic_v1/_api/windmill_query.py, examples/equipment_unit/client/_api/unit_procedure_query.py, examples/omni/_api/connection_item_a_query.py, examples/omni/_api/connection_item_b_query.py, examples/omni/_api/connection_item_c_query.py, examples/omni/_api/connection_item_d_query.py, examples/omni/_api/connection_item_e_query.py, examples/omni/_api/dependent_on_non_writable_query.py, examples/windmill/_api/blade_query.py, examples/windmill/_api/windmill_query.py, tests/test_integration/test_query.py
=> [PYG-82] Query on edge nodes

docs/CHANGELOG.md
=> build; changelog

cognite/pygen/_core/templates/_api_client_multi_model.py.jinja, cognite/pygen/_core/templates/_api_client_single_model.py.jinja, examples-pydantic-v1/equipment_unit_pydantic_v1/client/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/client/_api_client.py, examples/omni_multi/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py
=> [PYG-119] Fix .delete method docstring.

docs/usage/edge_properties.ipynb
=> Changed the import statement and  removed the .client. part

cognite/pygen/__init__.py, cognite/pygen/_build.py, docs/CHANGELOG.md, poetry.lock, pyproject.toml, tests/test_unit/test_generator/test_build.py
=> [PYG-48] Create wheel

docs/what_is_pygen.md
=> [PYG-148] docs; fix typos

.github/workflows/build.yml, .readthedocs.yaml, docs/requirements.txt, poetry.lock, pyproject.toml
=> [PYG-163] Remove docs req

cognite/pygen/_generator.py, docs/CHANGELOG.md
=> [PYG-162] Consistent writing

cognite/pygen/_core/generators.py, cognite/pygen/_core/models/data_classes.py, docs/CHANGELOG.md, tests/test_unit/test_api/test_generate_sdk.py, tests/test_unit/test_models/test_models.py
=> [PYG-105] Handle view without properties

tests/test_integration/test_query.py
Cannot recreate reported bug, closing task
=> [PYG-154]  Added test for self

docs/installation.md, docs/quickstart/cdf_notebook.ipynb, docs/quickstart/cdf_streamlit.md
=> [PYG-160, PYG-149] Added troubleshooting guide

docs/requirements.txt
=> docs: update dependencies

examples-pydantic-v1/omni_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_f.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_f_query.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/__init__.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_connection_item_f.py, examples/omni/_api/_core.py, examples/omni/_api/connection_item_f.py, examples/omni/_api/connection_item_f_query.py, examples/omni/_api_client.py, examples/omni/data_classes/__init__.py, examples/omni/data_classes/_connection_item_f.py, tests/data_models/Omni/containers/ConnectionBase.container.yaml, tests/data_models/Omni/containers/ConnectionDirectList.container.yaml, tests/data_models/Omni/model.yaml, tests/data_models/Omni/nodes.yaml, tests/data_models/Omni/views/ConnectionItemF.view.yaml
=> Add direct listable to Omni

docs/requirements.txt
=> docs: newest versions

docs/quickstart/ingestion.ipynb
=> [PYG-168] Update ingestion tutorial 👍

examples-pydantic-v1/equipment_unit_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock
=> 👷 Poetry update

docs/quickstart/where_to_start.md
=> Fix typos in where_to_start

cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/templates/data_classes_core.py.jinja, cognite/pygen/_settings.py, docs/CHANGELOG.md, examples/equipment_unit/data_classes/_core.py, examples/omni/data_classes/_core.py, examples/omni_multi/data_classes/_core.py, examples/scenario_instance/client/data_classes/_core.py, examples/windmill/data_classes/_core.py, tests/test_unit/test_models/test_models.py
=> [PYG-177] 👷Fix warnings

cognite/pygen/_core/generators.py, cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/models/fields/base.py, cognite/pygen/_core/templates/typed_classes.py.jinja
=> 🐛Bugs in Typed

.github/workflows/build.yml, .gitignore, dev.py, docs/installation.md, docs/quickstart/cdf_streamlit.md, examples-pydantic-v1/equipment_unit_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock, test-pyodide.js
=> [PYG-161, PYG-191] 😵CI test for pyodide

cognite/pygen/_core/models/fields/base.py, cognite/pygen/_core/models/fields/connections.py, cognite/pygen/_core/models/fields/primitive.py, cognite/pygen/_core/templates/typed_classes.py.jinja, examples-pydantic-v1/omni_typed_pydantic_v1/typed.py, examples/omni_typed/typed.py
=> [PYG-192] 🙂Load direct relation

cognite/pygen/_core/templates/data_classes_core.py.jinja, docs/CHANGELOG.md, examples-pydantic-v1/equipment_unit_pydantic_v1/data_classes/_core.py, examples-pydantic-v1/omni_multi_pydantic_v1/data_classes/_core.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_core.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/data_classes/_core.py, examples-pydantic-v1/windmill_pydantic_v1/data_classes/_core.py, examples/equipment_unit/data_classes/_core.py, examples/omni/data_classes/_core.py, examples/omni_multi/data_classes/_core.py, examples/scenario_instance/client/data_classes/_core.py, examples/windmill/data_classes/_core.py, tests/test_integration/test_retrieve.py
=> [PYG-196] 🐛 As write bug

cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/models/fields/connections.py, cognite/pygen/_core/templates/data_class_node.py.jinja, docs/CHANGELOG.md, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_e.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_e_inwards_single_property.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_e_query.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_f.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_f_outwards_single.py, examples-pydantic-v1/omni_pydantic_v1/_api/connection_item_f_query.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/__init__.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_connection_item_e.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_connection_item_f.py, examples/omni/_api/connection_item_e.py, examples/omni/_api/connection_item_e_inwards_single_property.py, examples/omni/_api/connection_item_e_query.py, examples/omni/_api/connection_item_f.py, examples/omni/_api/connection_item_f_outwards_single.py, examples/omni/_api/connection_item_f_query.py, examples/omni/data_classes/_connection_item_e.py, examples/omni/data_classes/_connection_item_f.py
=> [PYG-201] 🦘 Single edge with properties

cognite/pygen/_core/generators.py, cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/templates/api_class_node.py.jinja, cognite/pygen/_core/templates/api_core.py.jinja, docs/CHANGELOG.md, examples-pydantic-v1/equipment_unit_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api/main_interface.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api/sub_interface.py, examples-pydantic-v1/omni_pydantic_v1/_api/_core.py, examples-pydantic-v1/omni_pydantic_v1/_api/main_interface.py, examples-pydantic-v1/omni_pydantic_v1/_api/sub_interface.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api/_core.py, examples-pydantic-v1/windmill_pydantic_v1/_api/_core.py, examples/equipment_unit/_api/_core.py, examples/omni/_api/_core.py, examples/omni/_api/main_interface.py, examples/omni/_api/sub_interface.py, examples/omni_multi/_api/_core.py, examples/omni_multi/_api/main_interface.py, examples/omni_multi/_api/sub_interface.py, examples/scenario_instance/client/_api/_core.py, examples/windmill/_api/_core.py, tests/constants.py, tests/test_integration/test_retrieve.py, tests/test_unit/test_generator/test_generate_api_node.py
=> [PYG-103] 🦨Retrieve child classes

cognite/pygen/utils/mock_generator.py, docs/CHANGELOG.md, tests/test_unit/test_utils/test_mock_generator.py
=> [PYG-179] 🥾 Reset seed per view

cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/models/fields/base.py, tests/test_integration/test_typed_classes.py
=> 🦍Adjustment of typed.

cognite/pygen/_generator.py, tests/test_integration/test_typed_classes.py
=> 🦫fix: type hints

docs/quickstart/cdf_streamlit.md, examples-pydantic-v1/equipment_unit_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_sub_pydantic_v1/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock, pyproject.toml, tests/_system.yaml
=> [PYG-226]🕵️‍♂️Investigate generation bug

cognite/pygen/_core/generators.py, cognite/pygen/_core/templates/typed_classes.py.jinja, cognite/pygen/_generator.py, dev.py, docs/quickstart/cdf_streamlit.md, examples-pydantic-v1/equipment_unit_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_sub_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_typed_pydantic_v1/typed.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/omni_typed/typed.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock, pyproject.toml, tests/test_integration/test_typed_classes.py, tests/test_unit/conftest.py, tests/test_unit/test_generator/test_generate_typed_classes.py
=> [PYG-227] 🦣 Composition Option for Typed Classes

.gitignore, cognite/pygen/utils/mock_generator.py, docs/CHANGELOG.md, tests/test_integration/test_crud.py, tests/test_integration/test_typed_classes.py, tests/test_integration/test_upsert.py
=> [PYG-223] 😺Mock enums

docs/quickstart/cdf_streamlit.md, examples-pydantic-v1/equipment_unit_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_sub_pydantic_v1/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock, pyproject.toml
=> build: losen cognite-sdk

.github/workflows/build.yml, cognite/pygen/_core/templates/data_classes_core_query.py.jinja, dev.py, examples-pydantic-v1/equipment_unit_pydantic_v1/_api_client.py, examples-pydantic-v1/equipment_unit_pydantic_v1/data_classes/_core/query.py, examples-pydantic-v1/omni_multi_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_multi_pydantic_v1/data_classes/_core/query.py, examples-pydantic-v1/omni_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_pydantic_v1/data_classes/_core/query.py, examples-pydantic-v1/omni_sub_pydantic_v1/_api_client.py, examples-pydantic-v1/omni_sub_pydantic_v1/data_classes/_core/query.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/_api_client.py, examples-pydantic-v1/scenario_instance_pydantic_v1/client/data_classes/_core/query.py, examples-pydantic-v1/windmill_pydantic_v1/_api_client.py, examples-pydantic-v1/windmill_pydantic_v1/data_classes/_core/query.py, examples/equipment_unit/data_classes/_core/query.py, examples/omni/data_classes/_core/query.py, examples/omni_multi/data_classes/_core/query.py, examples/omni_sub/data_classes/_core/query.py, examples/scenario_instance/client/data_classes/_core/query.py, examples/windmill/data_classes/_core/query.py, tests/test_integration/test_query_method.py
=> [PYG-235] 🕵 Investigate query issues

.github/workflows/build.yml, cognite/pygen/_generator.py, docs/CHANGELOG.md, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock, pyproject.toml
=> [PYG-233] 🥳 Drop pydantic v1

docs/quickstart/notebook.ipynb, docs/usage/generation.ipynb
=> [PYG-243] 😛 Docs Clarify Client Creation

cognite/pygen/_core/templates/_api_client_multi_model.py.jinja, cognite/pygen/_core/templates/_api_client_single_model.py.jinja, cognite/pygen/utils/mock_generator.py, docs/CHANGELOG.md, docs/quickstart/cdf_streamlit.md, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock
=> [PYG-245] 😈Support delete by node ids

cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/templates/data_class_node.py.jinja, docs/CHANGELOG.md, examples/equipment_unit/data_classes/_unit_procedure.py, examples/omni/data_classes/_connection_item_a.py, examples/omni/data_classes/_connection_item_b.py, examples/omni/data_classes/_connection_item_c_node.py, examples/omni/data_classes/_connection_item_d.py, examples/omni/data_classes/_connection_item_e.py, examples/omni/data_classes/_connection_item_f.py, examples/omni/data_classes/_connection_item_g.py, examples/omni/data_classes/_dependent_on_non_writable.py, examples/omni_sub/data_classes/_connection_item_a.py, examples/omni_sub/data_classes/_connection_item_b.py, examples/omni_sub/data_classes/_connection_item_c_node.py, examples/windmill/data_classes/_blade.py, examples/windmill/data_classes/_nacelle.py, examples/windmill/data_classes/_windmill.py, tests/test_unit/test_resulting_sdk/test_data_class.py
=> [PYG-246] 👻 Tuple direct relation

cognite/pygen/_constants.py, cognite/pygen/utils/mock_generator.py, dev.py, docs/CHANGELOG.md, tests/data/write/ConnectionItemE.edge.yaml, tests/data/write/ConnectionItemF.edge.yaml, tests/data/write/ConnectionItemF.node.yaml, tests/data/write/ConnectionItemG.edge.yaml, tests/data/write/PrimitiveNullableListed.node.yaml, tests/omni_constants.py, tests/test_unit/test_utils/test_mock_generator.py
=> [PYG-252] 🧑‍🏫Mock properties edge

cognite/pygen/__init__.py, cognite/pygen/_core/query_execution.py, docs/CHANGELOG.md, tests/test_integration/test_query_execution.py
=> [PYG-261] 🏬Generic query method

cognite/pygen/_core/extract_query_code.py, cognite/pygen/_core/generators.py, cognite/pygen/_core/query_builder.py, cognite/pygen/_core/templates/data_classes_core_constants.py.jinja, cognite/pygen/_core/templates/data_classes_core_query.py.jinja, docs/CHANGELOG.md, examples/equipment_unit/data_classes/_core/constants.py, examples/equipment_unit/data_classes/_core/query.py, examples/omni/data_classes/_core/constants.py, examples/omni/data_classes/_core/query.py, examples/omni_multi/data_classes/_core/constants.py, examples/omni_multi/data_classes/_core/query.py, examples/omni_sub/data_classes/_core/constants.py, examples/omni_sub/data_classes/_core/query.py, examples/scenario_instance/client/data_classes/_core/constants.py, examples/scenario_instance/client/data_classes/_core/query.py, examples/windmill/data_classes/_core/constants.py, examples/windmill/data_classes/_core/query.py
=> [PYG-271] 🧑‍🍳 Search pagination

cognite/pygen/_core/templates/data_classes_core_query.py.jinja, dev.py, docs/CHANGELOG.md, docs/example_docs/core_apis.md, docs/example_docs/core_client.md, docs/example_docs/core_data_classes.md, docs/example_docs/index.md, examples/cognite_core/data_classes/_cognite_asset.py, examples/cognite_core/data_classes/_core/query.py, examples/equipment_unit/data_classes/_core/query.py, examples/omni/data_classes/_core/query.py, examples/omni_multi/data_classes/_core/query.py, examples/omni_sub/data_classes/_core/query.py, examples/scenario_instance/client/data_classes/_core/query.py, examples/windmill/data_classes/_core/query.py, mkdocs.yml, tests/conftest.py, tests/constants.py, tests/test_integration/conftest.py, tests/test_integration/test_query.py, tests/test_integration/test_query_method.py, tests/test_unit/conftest.py, tests/test_unit/test_generator/test_generate_data_class_node.py
=> [PYG-278]🙉  Reverse not included when query listing

cognite/pygen/_core/templates/data_classes_core_query.py.jinja, docs/CHANGELOG.md, docs/quickstart/cdf_notebook.ipynb, docs/quickstart/ingestion.ipynb, docs/quickstart/migration.ipynb, docs/quickstart/notebook.ipynb, docs/usage/aggregation.ipynb, docs/usage/creating_deleting.ipynb, docs/usage/edge_properties.ipynb, docs/usage/generation.ipynb, docs/usage/listing_filtering_retrieving.ipynb, docs/usage/querying.ipynb, docs/usage/searching.ipynb, docs/usage/timeseries.ipynb, examples/cognite_core/data_classes/_core/query.py, examples/equipment_unit/data_classes/_core/query.py, examples/omni/data_classes/_core/query.py, examples/omni_multi/data_classes/_core/query.py, examples/omni_sub/data_classes/_core/query.py, examples/scenario_instance/client/data_classes/_core/query.py, examples/windmill/data_classes/_core/query.py, tests/test_integration/test_query_method.py
=> [PYG-280, PYG-279] 💌Pygen branding

docs/CHANGELOG.md, docs/quickstart/cdf_streamlit.md, examples/cognite_core/_api_client.py, examples/equipment_unit/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/scenario_instance/client/_api_client.py, examples/windmill/_api_client.py, poetry.lock, pyproject.toml
=> [PYG-283] ⬆ Lower bound inflect raised

cognite/pygen/_constants.py, cognite/pygen/_core/models/fields/__init__.py, cognite/pygen/_core/models/fields/cdf_reference.py, cognite/pygen/_core/models/fields/connections.py, cognite/pygen/_core/models/fields/primitive.py, cognite/pygen/_core/models/filter_methods.py, cognite/pygen/utils/mock_generator.py, docs/CHANGELOG.md, examples/cognite_core/_api/cognite_asset.py, examples/cognite_core/data_classes/_cognite_asset.py, examples/cognite_core/data_classes/_cognite_file.py, examples/wind_turbine/data_classes/_data_sheet.py
=> [PYG-259] 🌑 Skip read-only properties

cognite/pygen/_core/models/fields/base.py, cognite/pygen/_core/models/fields/connections.py, cognite/pygen/_warnings.py, docs/CHANGELOG.md, tests/test_unit/test_api/test_generate_sdk.py
=> [PYG-295] 🤨 Edge source not in Model

docs/quickstart/cdf_streamlit.md
=> docs; fix outdated

.pre-commit-config.yaml, cognite/pygen/_core/models/data_classes.py, cognite/pygen/_core/templates/api_core.py.jinja, docs/CHANGELOG.md, examples/cognite_core/_api/_core.py, examples/omni/_api/_core.py, examples/omni_multi/_api/_core.py, examples/omni_sub/_api/_core.py, examples/wind_turbine/_api/_core.py, tests/conftest.py, tests/test_integration/test_aggregate.py, tests/test_integration/test_crud.py, tests/test_integration/test_graphql_query.py, tests/test_integration/test_list.py, tests/test_integration/test_query.py, tests/test_integration/test_query_builder.py, tests/test_integration/test_query_execution.py, tests/test_integration/test_select_method.py, tests/test_integration/test_typed_classes.py, tests/test_integration/test_upsert.py, tests/test_unit/conftest.py, tests/test_unit/test_generator/test_generators.py, tests/test_unit/test_models/conftest.py, tests/test_unit/test_models/test_fields.py, tests/test_unit/test_omni_coverage.py, tests/test_unit/test_resulting_sdk/test_core_data_classes.py, tests/test_unit/test_resulting_sdk/test_data_class.py, tests/test_unit/test_resulting_sdk/test_import_sdks.py, tests/test_unit/test_utils/test_mock_generator.py
=> [PYG-209]🤪MyPy on Tests

examples/omni/_api/cdf_external_references_listed_timeseries.py, examples/wind_turbine/_api/metmast_temperature.py, examples/wind_turbine/_api/metmast_tilt_angle.py, examples/wind_turbine/_api/metmast_wind_speed.py
=> Regen SDKs

cognite/pygen/_query/interface.py, cognite/pygen/_query/processing.py, cognite/pygen/_query/step.py, examples/cognite_core/data_classes/_core/query/processing.py, examples/cognite_core/data_classes/_core/query/step.py, examples/omni/data_classes/_core/query/processing.py, examples/omni/data_classes/_core/query/step.py, examples/omni_multi/data_classes/_core/query/processing.py, examples/omni_multi/data_classes/_core/query/step.py, examples/omni_sub/data_classes/_core/query/processing.py, examples/omni_sub/data_classes/_core/query/step.py, examples/wind_turbine/data_classes/_core/query/processing.py, examples/wind_turbine/data_classes/_core/query/step.py, tests/test_integration/test_query_execution.py
=> [prep PYG-218] 🤪Extend query functionality

.github/workflows/build.yml, docs/docs-dev/docs_query.ipynb, docs/docs-dev/query_filter.ipynb, docs/requirements.txt, mkdocs.yml
=> [PYG-275] 😪 Docs filtering

cognite/pygen/_core/templates/data_classes_core_cdf_external.py.jinja, docs/CHANGELOG.md, docs/usage/querying.ipynb, examples/cognite_core/data_classes/_core/cdf_external.py, examples/omni/data_classes/_core/cdf_external.py, examples/omni_multi/data_classes/_core/cdf_external.py, examples/omni_sub/data_classes/_core/cdf_external.py, examples/wind_turbine/data_classes/_core/cdf_external.py, tests/test_integration/test_graphql_query.py
=> [PYG-309] 😴 GraphQL get latest

.github/workflows/build.yml
=> [PYG-228] 🕵 ci: testing 312

.github/CODEOWNERS
=> [PYG-330] Neat-team codeowners

cognite/pygen/_generator.py, cognite/pygen/_settings.py, cognite/pygen/cli.py, docs/CHANGELOG.md
=> [PYG-334] Change default formatting

cognite/pygen/_core/models/fields/cdf_reference.py, cognite/pygen/_core/models/fields/primitive.py, cognite/pygen/_core/templates/data_classes_core_base.py.jinja, docs/CHANGELOG.md, examples/cognite_core/data_classes/_cognite_360_image_station.py, examples/cognite_core/data_classes/_cognite_3_d_model.py, examples/cognite_core/data_classes/_cognite_3_d_revision.py, examples/cognite_core/data_classes/_cognite_annotation.py, examples/cognite_core/data_classes/_cognite_point_cloud_volume.py, examples/cognite_core/data_classes/_cognite_time_series.py, examples/cognite_core/data_classes/_core/base.py, examples/omni/data_classes/_core/base.py, examples/omni_multi/data_classes/_core/base.py, examples/omni_sub/data_classes/_core/base.py, examples/wind_turbine/data_classes/_core/base.py, examples/wind_turbine/data_classes/_sensor_time_series.py, tests/test_unit/test_resulting_sdk/test_core_api.py
=> [PYG-336] Flexible response

.github/workflows/prepare-release.yaml, .github/workflows/release.yaml, dev.py, docs/CHANGELOG.md
=> [PYG-333] 🤖 New release flow

.github/pull_request_template.md, .github/workflows/release.yaml, dev.py
Allow Improved header in changelog. In addition, no longer require a changelog entry when you select `skip` in the bump
=> 🤖 Allow Improved Header in Changelog

.github/workflows/build.yml, dev.py
=> 🤖fix: allow upper case

cognite/pygen/_core/templates/_api_client_multi_model.py.jinja, cognite/pygen/_core/templates/_api_client_single_model.py.jinja, cognite/pygen/_query/interface.py, cognite/pygen/utils/mock_generator.py, examples/cognite_core/_api_client.py, examples/omni/_api_client.py, examples/omni_multi/_api_client.py, examples/omni_sub/_api_client.py, examples/wind_turbine/_api_client.py
Requested by Cogniter to log app usage for Pygen.
- Client name is preserved with prefix for the client config passed to pygen
=> [PYG-349]  📝 App logging

cognite/pygen/_core/templates/data_classes_core_query_select.py.jinja, examples/cognite_core/data_classes/_core/query/select.py, examples/omni/data_classes/_core/query/select.py, examples/omni_multi/data_classes/_core/query/select.py, examples/omni_sub/data_classes/_core/query/select.py, examples/wind_turbine/data_classes/_core/query/select.py, tests/test_unit/test_resulting_sdk/test_select.py
This is an hidden feature that is used for debugging.
=> [PYG-358] 🤓 Dump yaml

.gitattributes
Introduced `.gitattributes` file to mark generated code.
=> build: introduce git attributes file

tests/utils.py
This is a pure helper that is not part of the package. It is just to easily instantiate a CogniteClient which I use when debugging.
=> 🔨Add helper

.github/CODEOWNERS
Add backend atlas ai team as owners
=> Add backend atlas ai team as owners

.github/pull_request_template.md
Inform the reviewer that `examples/` is generated.
=> [PYG-408] Update PR templates
